server {
  listen 80;
  server_name localhost;

  location / {
    # Onde os arquivos do React (gerados pelo Vite) estão salvos
    root /usr/share/nginx/html;
    index index.html index.htm;
    
    # A mágica do React Router acontece nesta linha:
    try_files $uri $uri/ /index.html;
  }

  # Desativa logs de arquivos não encontrados (opcional, mas deixa os logs limpos)
  error_log /var/log/nginx/error.log;
  access_log /var/log/nginx/access.log;
}